# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d33335089ee99ea9520d956501ff2e6bda8b5a12d98dd4d707c9c540339937a926290046dffd535dafc57c4b2f28c6421fd8d6f04ab5d5e18159c028d2a8f162

test:
  secret_key_base: f0453988a0abd73874374327de4f7db70ff25fc82ddccf9dff0c9789965826a1a86a7217a5d219b693ba0614c78199f12203f0e43ddb75a005e93ae8127c1c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
